# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Build docker CLI
        env:
          DOCKER_VERSION: 20.10.5
        run: |
          $env:GOPATH="$env:USERPROFILE\go"
          git clone -q --branch=v${env:DOCKER_VERSION} --single-branch https://github.com/docker/cli.git ${env:GOPATH}\src\github.com\docker\cli
          
          cd ${env:GOPATH}\github.com\docker\cli
          powershell -File .\scripts\make.ps1 -Binary
        shell: powershell
