# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Build docker CLI
        env:
          VERSION: 20.10.5
        run: |
          curl.exe -o cli.tar.gz -L https://github.com/docker/cli/archive/refs/tags/v${env:VERSION}.tar.gz
          tar.exe -x -f cli.tar.gz
          
          $env:GOPATH="$env:USERPROFILE\go"
          mkdir $env:GOPATH\github.com\docker
          move .\cli-${env:VERSION} $env:GOPATH\github.com\docker\cli
          cd $env:GOPATH\github.com\docker\cli
          powershell -File .\scripts\make.ps1 -Binary
        shell: powershell
